<h2>Weather</h2>
<label for="city"><?php echo __('Location') ?></label>
<br>
<input type="text" id="city" name="city" title="<?php echo __('City Name') ?>">
<br>
<br>
<a href="javascript:void(0)" id="mc_get_dynamic_value" class="action submit primary">See Weather</a>

<div>

    <!-- LOCATION -->
    <div class="row text-center">
        <div class="col-lg-12">
            <h1 class="city"></h1>
            <h4 class="country"></h4>
        </div>
    </div>
    <!-- DATA AREA -->
    <div>
        <h4 class="description"></h4>
        <h4 class="temp"></h4>
        <h4 class="feels-like"></h4>
        <h4 class="pressure"></h4>
        <h4 class="humidity"></h4>
        <h4 class="wind-speed"></h4>
        <h4 class="sunrise"></h4>
        <h4 class="sunset"></h4>
    </div>

</div>
<table id="weatherData">
    <thead>
        <tr>
            <th><?= __('City') ?></th>
            <th><?= __('Country') ?></th>
            <th><?= __('Description') ?></th>
            <th><?= __('Temperature') ?></th>
            <th><?= __('Feels like') ?></th>
            <th><?= __('Pressure') ?></th>
            <th><?= __('Humidity') ?></th>
            <th><?= __('Wind Speed') ?></th>
            <th><?= __('Sunrise') ?></th>
            <th><?= __('Sunset') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $collectionData = $block->getWeatherCollection();
        foreach ($collectionData as $collection) :
        ?>
            <tr>
                <td><?= $collection->getCity(); ?></td>
                <td><?= $collection->getCountry(); ?></td>
                <td><?= $collection->getDescription(); ?></td>
                <td><?= $collection->getTemperature(); ?></td>
                <td><?= $collection->getFeelsLike(); ?></td>
                <td><?= $collection->getPressure(); ?></td>
                <td><?= $collection->getHumidity(); ?></td>
                <td><?= $collection->getWindSpeed(); ?></td>
                <td><?= $collection->getSunrise(); ?></td>
                <td><?= $collection->getSunset(); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>

</table>
<form method="post">
    <input class="action submit primary" type="submit" name="pdf" value="Convert To PDF" /><br />
</form>



<script>
    require(['jquery'], function($) {
        //on submition
        $('#mc_get_dynamic_value').on('click', function(e) {
            //initialise data
            let field_one = $("#city").val();
            //weather app api ps. no seperate variable for the key 
            let API = "http://api.openweathermap.org/data/2.5/weather?q=" + field_one + "&units=metric" + "&appid=8d0bef5c6d7e4ac1577361232d0a4bc0";
            //dt will be the data sent to controller
            let dt = '';
            //controller url
            let api_controller_url = "<?=
                                        /** @noEscape */
                                        $block->getUrl('weatherapp/index/curlhandler') ?>";
            //fetch api
            fetch(API)
                // when we get response from server
                .then(response => {
                    // return respon as json
                    return response.json();
                })
                .then(data => {
                    dt = data;
                    // log the data
                    console.log(dt);
                    // set the data in front end
                    $('.city').text(data.name);
                    $('.country').text('Country: ' + data.sys.country);
                    $('.description').text('Description: ' + data.weather.description);
                    $('.temp').text('Temperature: ' + data.main.temp + " ℃");
                    $('.feels-like').text('Feels like: ' + data.main.feels_like + " ℃");
                    $('.pressure').text('Pressure: ' + data.main.pressure);
                    $('.humidity').text('Humidity: ' + data.main.humidity);
                    $('.wind-speed').text('Wind speed: ' + data.wind.speed);
                    $('.sunrise').text('Sunrise: ' + data.sys.sunrise);
                    $('.sunset').text('Sunset: ' + data.sys.sunset);
                    $("div[data-role='spinner']").hide();
                    $("input[name='dynamic_value']").val(data).change();
                    // add data to the table
                    $('#weatherData tbody').append(' <tr><td>' + data.name + '</td><td>' + data.sys.country + '</td><td>' + data.weather.description + '</td><td> ' + data.main.temp + ' </td><td>' + data.main.feels_like + '</td><td>' + data.main.pressure + '</td><td>' + data.main.humidity + '</td><td>' + data.wind.speed + '</td><td>' + data.sys.sunrise + '</td><td>' + data.sys.sunset + '</td></tr>');
                    //send the recieved weather data to controller with ajax 
                    $.ajax({
                        url: api_controller_url,
                        type: 'POST',
                        data: {
                            weather_data: dt,
                            format: 'json',
                        },
                        dataType: 'json',
                        success: function(data) {
                            console.log(data);

                        },
                        error: function(request, error) {
                            console.error('Dynamic Value Fetching Error!');
                            console.log(request.responseText);
                        }
                    });

                });

        });
    });
</script>
<style>
        table {
            margin: 25px 0;
            width: 200px;
        }
  
        table th, table td {
            padding: 10px;
            text-align: center;
        }
  
        table, th, td {
            border: 1px solid grey;
        }
    </style>